spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/XE
    username: bdadm
    password: bdadm
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa: #JPA 설정
    hibernate:
      ddl-auto: none  # 없으면 만들고 있으면 그대로 사용
    properties:
      hibernate:
        show_sql: true                #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        format_sql: true              #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        use_sql_comments: true        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
  mvc:
    view:
      suffix: .html

logging.level:
  org.hibernate.SQL: debug
  com.test.config.demo: debug

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh"]